### PR TITLE
Allow more control from CameraActivity when hitting flashpoint

### PR DESCRIPTION
**Pull request by ramdroid**
In my project I have an Activity extending CameraActivity. When the user hits the flashpoint (WillTakePicture event) I need to save the current device orientation (Azimuth, Pitch, Roll) and return it to the calling activity (using getResultIntent() to add extras).

I don't know if there's a better way to do this, or if it's not suitable at all. But you tell me ;)

### CODE REVIEW

**Comment by commonsguy** [comment]
I don't have a problem with what you're doing here. However, as I note in [the project contribution guidelines](https://github.com/commonsguy/cwac-cam2/blob/master/.github/CONTRIBUTING.md#contributing-code), I cannot really accept significant pull requests directly. I will look to implement a similar hook that you can use.

And, if what you are seeking is covered by [this bit of documentation](https://developer.android.com/guide/topics/sensors/sensors_position.html#sensors-pos-orient), I may add an option to collect them for you, as that doesn't seem especially difficult.

Thanks!

**Comment by ramdroid** [comment]
Yes, the SensorManager data is exactly what I'm collecting. Would be great if that's already built-in.

**Comment by commonsguy** [comment]
I had thought that there might be EXIF headers for the sensor readings that I could fill in, but I cannot find any. So, I'm implementing a hook for you, reminiscent of your implementation. The differences:

- The event name is `PictureCaptureStartEvent` instead of `WillTakePicture`.

- I am not handling the event anywhere, so you can decide the thread policy that makes sense for you. Your code uses `MAIN`; I would think that you really want the event to be delivered on the posting thread, so that actual picture capture is blocked until you can schedule your work.

- I went with `buildResultIntent()` instead of `getResultIntent()`.

**Comment by commonsguy** [comment]
Addressed in v0.7.6 as noted above. Thanks for the suggestion!

**Pull request closed without merging**
