### PR TITLE
Zoom support.

### PR DESCRIPTION
**Pull request by daniribalbert**
Hey, I've added zoom support for both Camera and Camera2.
Feel free to use it as inspiration for future releases :)

### CODE REVIEW

**Comment by commonsguy** [comment]
Wow, that's... extensive! :-)

Just to confirm that I'm reading it correctly, you're going the pinch-zoom route for controlling the zoom level, right?

Many thanks!

**Comment by daniribalbert** [comment]
That's right.

ScaleGestureDetector checks pinch-zoom => EventBus sends a ZoomEvent to CameraController => CameraEngine handles zoom :)

**Comment by commonsguy** [comment]
I'll definitely look at this and use it as a source of implementation suggestions. Issue #18 is the tracking issue for official zoom support, in case you want to keep an eye on it.

Thanks again!

**Comment by commonsguy** [comment]
OK, the next update to this library will contain zoom support. I have [checked in code](https://github.com/commonsguy/cwac-cam2/commit/f6e1e4285a264c532777af0d37643f74daa77687) that handles this for the `ClassicCameraEngine` (and general support). I hope to add support for `CameraTwoEngine` before release.

There are some noteworthy differences in how I approached it versus your pull request:

- It is opt-in. There is a `zoomStyle()` method on the `CameraActivity.IntentBuilder` that you need to call to enable zoom.

- It supports either pinch-zoom or a `SeekBar`, via `ZoomStyle.PINCH` and `ZoomStyle.SLIDER`. Personally, I don't like pinch-zoom.

- I am using the smooth zoom APIs on the original `Camera` class, where available. Or at least, in theory I am, as it seems like most devices don't support that.

- My pinch and `SeekBar` code is on the fragment, not the activity.

So, stay tuned to issue #18 for the rest. And, once again, even though I am about to ruthlessly close it, thanks for the pull request!

**Pull request closed without merging**
